import React, { useMemo } from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import MapView, { PROVIDER_GOOGLE } from 'react-native-maps';
import { Ionicons } from '@expo/vector-icons';
import { getAllRoutes } from '../services/routes';
import { theme } from '../styles/global-styles';
import RouteBadge from '../components/RouteBadge';
import RouteMapLayers from '../components/RouteMapLayers';

const iloRegion = { latitude: -17.6428, longitude: -71.3452, latitudeDelta: 0.035, longitudeDelta: 0.035 };
export default function MapOverviewScreen({ navigation }) {
    const routes = useMemo(() => getAllRoutes().filter((item) => item.available && item.coordinates?.length), []);
    return (
        <SafeAreaView style={styles.safeArea} edges={['top']}>
            <MapView provider={PROVIDER_GOOGLE} initialRegion={iloRegion} style={styles.map} showsUserLocation>
                {routes.map((item) => <RouteMapLayers key={item.id} route={item} showStops={false} />)}
            </MapView>
            <View style={styles.top}><View style={styles.brand}><Ionicons name="bus-outline" size={20} color={theme.colors.primary} /><Text style={styles.brandText}>Avanza Ilo</Text></View><TouchableOpacity accessibilityRole="button" accessibilityLabel="Buscar ruta" onPress={() => navigation.navigate('SearchResults')} style={styles.searchButton}><Ionicons name="search-outline" size={21} color={theme.colors.textDark} /></TouchableOpacity></View>
            <View style={styles.mapHint}><Ionicons name="navigate" size={17} color={theme.colors.surface} /><Text style={styles.mapHintText}>Las flechas indican el sentido de la combi</Text></View>
            <View style={styles.sheet}><View style={styles.handle} /><Text style={styles.sheetTitle}>¿Por dónde pasa tu combi?</Text><Text style={styles.sheetSub}>Elige una ruta para ver sus paraderos, sentido y tiempo estimado.</Text><View style={styles.routeRow}>{routes.slice(0, 3).map((item) => <TouchableOpacity key={item.id} onPress={() => navigation.navigate('RouteDetails', { routeName: item.nombre })} style={[styles.routeChip, { borderColor: item.color }]}><View style={[styles.routeLine, { backgroundColor: item.color }]} /><RouteBadge route={item.nombre} color={item.color} size="small" /><Text style={styles.routeName}>Ruta {item.nombre}</Text></TouchableOpacity>)}</View><TouchableOpacity onPress={() => navigation.navigate('NearbyStops')} style={styles.nearby}><View style={styles.nearbyIcon}><Ionicons name="location" size={17} color={theme.colors.primary} /></View><Text style={styles.nearbyText}>Ver paraderos cercanos</Text><Ionicons name="chevron-forward" size={18} color={theme.colors.textLight} /></TouchableOpacity></View>
        </SafeAreaView>
    );
}
const styles = StyleSheet.create({ safeArea: { flex: 1, backgroundColor: theme.colors.background }, map: { ...StyleSheet.absoluteFillObject }, top: { flexDirection: 'row', justifyContent: 'space-between', padding: 16 }, brand: { height: 45, paddingHorizontal: 14, borderRadius: 14, flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.border, ...theme.shadows.base }, brandText: { color: theme.colors.primary, fontWeight: '800', fontSize: 16 }, searchButton: { height: 45, width: 45, borderRadius: 14, backgroundColor: theme.colors.surface, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: theme.colors.border, ...theme.shadows.base }, mapHint: { position: 'absolute', top: 76, left: 16, flexDirection: 'row', alignItems: 'center', gap: 7, backgroundColor: '#1B2730E8', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 18 }, mapHintText: { color: theme.colors.surface, fontSize: 13, fontWeight: '700' }, sheet: { marginTop: 'auto', borderTopLeftRadius: 28, borderTopRightRadius: 28, backgroundColor: theme.colors.surface, padding: 20, ...theme.shadows.heavy }, handle: { alignSelf: 'center', width: 42, height: 4, borderRadius: 2, backgroundColor: '#D9E0E3', marginBottom: 14 }, sheetTitle: { color: theme.colors.textDark, fontSize: 21, fontWeight: '800' }, sheetSub: { color: theme.colors.textMuted, fontSize: 15, lineHeight: 20, marginTop: 5 }, routeRow: { flexDirection: 'row', gap: 8, marginTop: 16 }, routeChip: { flex: 1, minHeight: 80, gap: 6, alignItems: 'center', justifyContent: 'center', borderRadius: 14, backgroundColor: theme.colors.background, borderWidth: 1.5, overflow: 'hidden' }, routeLine: { position: 'absolute', top: 0, left: 0, right: 0, height: 5 }, routeName: { fontSize: 13, fontWeight: '800', color: theme.colors.textDark }, nearby: { marginTop: 16, minHeight: 54, paddingHorizontal: 12, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 14, flexDirection: 'row', alignItems: 'center', gap: 10 }, nearbyIcon: { width: 31, height: 31, borderRadius: 16, backgroundColor: theme.colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, nearbyText: { flex: 1, color: theme.colors.textDark, fontSize: 16, fontWeight: '700' } });
